<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>Search booking</h1>
    <p><?php echo $this->tag->linkTo(["booking/new", "Create booking"]) ?></p>
</div>

<?php echo $this->getContent() ?>

<form action="booking/search" class="form-horizontal" method="get">
    <div class="form-group">
    <label for="fieldId" class="col-sm-2 control-label">Id</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id", "type" => "number", "class" => "form-control", "id" => "fieldId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldBookingdate" class="col-sm-2 control-label">Bookingdate</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["bookingdate", "type" => "date", "class" => "form-control", "id" => "fieldBookingdate"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldStarttime" class="col-sm-2 control-label">Starttime</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["starttime", "size" => 30, "class" => "form-control", "id" => "fieldStarttime"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldEndtime" class="col-sm-2 control-label">Endtime</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["endtime", "size" => 30, "class" => "form-control", "id" => "fieldEndtime"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldMemberid" class="col-sm-2 control-label">Memberid</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["memberid", "type" => "number", "class" => "form-control", "id" => "fieldMemberid"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCourtid" class="col-sm-2 control-label">Courtid</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["courtid", "type" => "number", "class" => "form-control", "id" => "fieldCourtid"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldFee" class="col-sm-2 control-label">Fee</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["fee", "type" => "number", "class" => "form-control", "id" => "fieldFee"]) ?>
    </div>
</div>


    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
        </div>
    </div>
</form>
