<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["booking", "Go Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Create booking</h1>
</div>

<?php echo $this->getContent(); ?>

<form action="booking/create" class="form-horizontal" method="post">
    <div class="form-group">
    <label for="fieldBookingdate" class="col-sm-2 control-label">Bookingdate</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["bookingdate", "type" => "date", "class" => "form-control", "id" => "fieldBookingdate"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldStarttime" class="col-sm-2 control-label">Starttime</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["starttime", "size" => 30, "class" => "form-control", "id" => "fieldStarttime"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldEndtime" class="col-sm-2 control-label">Endtime</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["endtime", "size" => 30, "class" => "form-control", "id" => "fieldEndtime"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldMemberid" class="col-sm-2 control-label">Memberid</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["memberid", "type" => "number", "class" => "form-control", "id" => "fieldMemberid"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCourtid" class="col-sm-2 control-label">Courtid</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["courtid", "type" => "number", "class" => "form-control", "id" => "fieldCourtid"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldFee" class="col-sm-2 control-label">Fee</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["fee", "type" => "number", "class" => "form-control", "id" => "fieldFee"]) ?>
    </div>
</div>


    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
        </div>
    </div>
</form>
