<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["court", "Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Edit court</h1>
</div>

<?php echo $this->getContent(); ?>

<form action="court/save" class="form-horizontal" method="post">
    <div class="form-group">
    <label for="fieldSurface" class="col-sm-2 control-label">Surface</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["surface", "size" => 30, "class" => "form-control", "id" => "fieldSurface"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldFloodlights" class="col-sm-2 control-label">Floodlights</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["floodlights", "size" => 30, "class" => "form-control", "id" => "fieldFloodlights"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIndoor" class="col-sm-2 control-label">Indoor</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["indoor", "size" => 30, "class" => "form-control", "id" => "fieldIndoor"]) ?>
    </div>
</div>


    <?php echo $this->tag->hiddenField("id") ?>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
        </div>
    </div>
</form>
